language: java
jdk:
- oraclejdk8

after_success:
  - mvn clean source:jar javadoc:jar
  - test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && mvn deploy --settings travis-settings.xml

branches:
  only:
    - master
      # Build tags that match this regex in addition to building the master branch.
    - /-[0-9]+\.[0-9]+\.[0-9]+$/
